spring:
  cloud:
    config:
      server:
        native:
#          search-locations: file:///D:/B
          searchLocations: classpath:/shared

  profiles:
     active: native

  application:
    name: config-service

#server:
#  port: 8888