endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    workspaces-api:
      path: /workspaces/**
      stripPrefix: false
#      url: http://localhost:9090
#      serviceId: workspaces-api

#    employees-api: /employees/**

#ribbon:
#  eureka:
#    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9292/eureka/
    register-with-eureka: true
    fetch-registry: true

#workspaces-api:
#  ribbon:
#    listOfServers: http://localhost:9090
#    ServerListRefreshInterval: 15000

#server:
#  port: 8081